swagger: '2.0'
info:
  description: myauth API
  version: 1.0.0
  title: myGuard-auth
host: rocky-eyrie-99010.herokuapp.com
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
tags:
- name: Auth
  description: Authorization API
paths:
  /auth/registration:
    post:
      summary: Registration user
      security: []
      tags: [Auth]
      parameters:
      - in: body
        name: User
        description: registration user
        required: true
        schema:
          $ref: '#/definitions/UserAuth'
      responses:
        "200":
          description: User has been registered
          schema:
            $ref: '#/definitions/registrationResponce'
        "400":
          description: Bad Request
        "500":
          description: Server error
  /auth/login:
    post:
      summary: Login user
      security: []
      tags: [Auth]
      parameters:
      - in: body
        name: User
        description: User login
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          description: User has been login
          schema:
            $ref: '#/definitions/registrationResponce'
        "400":
          description: Bad Request
        "500":
          description: Server error
  /auth/logout:
    post:
      summary: Logout user
      security:
        - Bearer: []
      tags: [Auth]
      responses:
        "200":
          description: User has been login
        "401":
          description: Access denied
        "500":
          description: Server error
  /auth/refresh:
    get:
      summary: Refresh token
      security:
        - Bearer: []
      tags: [Auth]   
      responses:
        "200":
          description: take new refresh token
          schema:
            $ref: '#/definitions/Token'
        "401":
          description: Access denied
        "500":
          description: Server error
  /auth/check:
    get:
      summary: check 
      security: 
        - Bearer: []
      tags: [Auth]
      responses:
        "200":
          description: token status
        "401":
          description: Bad Request
        "500":
          description: Server error
definitions:
    UserAuth:
      type: object
      required:
      - email
      - password
      - name
      properties:
        email:
          type: string
          description: User email
        password:
          type: string
          description: User password
        name:
          type: string
          description: User name
      example:
        email: 1258@gmail.com
        password: ehhwetj651he
        name: Genadiy
    Login:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: User email
        password:
          type: string
          description: User password
      example:
          email: 1258@gmail.com
          password: ehhwetj651he
    registrationResponce:
      type: object
      required:
        - accessToken
        - refreshToken
        - userId
        - role
      properties:
        accessToken:
          type: string
          description: accessToken
        refreshToken:
          type: string
          description: refreshToken
        userId:
          type: string
          description: user id
        role:
          type: string
          description: role
      example:
        email: 1258@gmail.com
        password: ehhwetj651he
    Token:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
          description: accessToken
        refreshToken:
          type: string
          description: refreshToken
      example:
        accessToken: a155cac0-a85a-11ec-9fcd-657971076650
        refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJpYXQiOjE2NDc3ODY3NzQsImV4cCI6MTY1MDM3ODc3NH0.-iI2u4xFIcXOnyc6lM_MlLx1DqHnu27DlIWwkRDPTHc
